export { default as NewsService } from './news';
export { default as AuthService } from './auth';
export { default as UsersService } from './users';
export { default as BooksService } from './books';
export { default as OTPService } from './auth/otp';
export { default as GenresService } from './genres';
export { default as AuthorsService } from './authors';
export { default as ReviewsService } from './reviews';
export { default as CategoriesService } from './categories';