export { default as NewsService } from './news';
export { default as AuthService } from './auth';
export { default as UsersService } from './users';
export { default as BooksService } from './books';
export { default as OTPService } from './auth/otp';
export { default as GenresService } from './genres';
export { default as AuthorsService } from './authors';
export { default as ReviewsService } from './reviews';
export { default as CategoriesService } from './categories';
export { default as RegionsService } from './user-api/regions'
export { default as PaymentMethodsService } from './user-api/payment-methods'
export { default as DeliveryMethodsService } from './user-api/delivery-methods'