export { default as newsRouting } from './news';
export { default as authRouting } from './auth';
export { default as usersRouting } from './users';
export { default as booksRouting } from './books'; 
export { default as genresRouting } from './genres';
export { default as uploadRouting } from './upload';
export { default as bannersRouting } from './banners'
export { default as authorsRouting } from './authors';
export { default as reviewsRouting } from './reviews';
export { default as userApiRouting } from './user-api'
export { default as categoriesRouting } from './categories';
export { default as statisticsRouting } from './statistics';