export { default as NewsModel } from './news';
export { default as UserModel } from './user';
export { default as GenreModel } from './genre';
export { default as AuthorModel } from './author';
export { default as RegionModel } from './user-api/region'
export { default as DistrictModel } from './user-api/district'
export { default as PromocodeModel } from './user-api/promocode'
export { default as PaymentMethodModel } from './user-api/payment-method'
export { default as DeliveryMethodModel } from './user-api/delivery-method'